FROM maven:3.8.4-openjdk-8 AS build
COPY . /app
WORKDIR /app
ENTRYPOINT ["mvn", "clean", "verify"]

FROM openjdk:8-jre-slim
WORKDIR /app
COPY --from=build /app/application.properties /app/application.properties
COPY --from=build /app/target/embedash-1.1-SNAPSHOT.jar /app/target/embedash-1.1-SNAPSHOT.jar
CMD ["java", "-jar", "/app/target/embedash-1.1-SNAPSHOT.jar", "--spring.config.location=/app/application.properties"]
